library(readr)
library(tidyverse)
spotify_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2020/2020-01-21/spotify_songs.csv')
spotify_songs
names(spotify_songs)
install.packages("ggplot")
name_pop <- c(spotify_songs$track_name, spotify_songs$track_popularity)
ggplot(name_pop)
ggplot(spotify_songs)
ggplot(spotify_songs, aes(track_popularity, danceability))
ggplot(spotify_songs, aes(track_popularity, danceability)) +
  geom_point()
ggplot(spotify_songs, aes(danceability, track_popularity))
ggplot(spotify_songs, aes(danceability, track_popularity)) + geom_bin2d()
ggplot(spotify_songs, aes(danceability, track_popularity)) + geom_point()
spotify_songs_filter = spotify_songs %>%
  dplyr::filter(track_popularity>10)
spotify_songs_filter
ggplot(spotify_songs_filter, aes(danceability, track_popularity)) + geom_point()
spotify_songs_filter = spotify_songs %>%
  dplyr::filter(track_popularity>5)
ggplot(spotify_songs_filter, aes(danceability, track_popularity)) + geom_bin2d()
spotify_songs_minor = spotify_songs_filter %>%
  dplyr::filter(mode=0)
spotify_songs_minor = spotify_songs_filter %>%
  dplyr::filter(mode==0)
spotify_songs_major = spotify_songs_filter %>%
  dplyr::filter(mode==1)
ggplot(spotify_songs_major, aes(energy)) + geom_histogram()
ggplot(spotify_songs_minor, aes(energy)) + geom_histogram()
ggplot(spotify_songs_minor, aes(energy)) + geom_histogram()
ggplot(spotify_songs_major, aes(energy)) + geom_histogram()
ggplot(spotify_songs_major, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_minor, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_major, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_major, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_minor, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_major, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_minor, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_major, aes(track_popularity)) + geom_histogram()
ggplot(spotify_songs_major, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_minor, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_major, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_minor, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_major, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_minor, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_minor, aes(valence)) + geom_histogram()
ggplot(spotify_songs_major, aes(valence)) + geom_histogram()
ggplot(spotify_songs_minor, aes(valence)) + geom_histogram()
ggplot(spotify_songs_minor, aes(tempo)) + geom_histogram()
ggplot(spotify_songs_major, aes(tempo)) + geom_histogram()
ggplot(spotify_songs_minor, aes(tempo)) + geom_histogram()
ggplot(spotify_songs_major, aes(tempo)) + geom_histogram()
ggplot(spotify_songs_minor, aes(tempo)) + geom_histogram()
ggplot(spotify_songs_major, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_minor, aes(danceability)) + geom_histogram()
ggplot(spotify_songs_filter, aes(danceability, track_popularity)) + geom_bin2d()
summary(spotify_songs_minor$track_popularity)
summary(spotify_songs_major$track_popularity)
c(summary(spotify_songs_major$danceability), summary(spotify_songs_minor$danceability))